matrix:
  include:
  - language: python
    python:
      "3.8.2"
    install:
      - "pip install -r requirements.txt"
    services: 
      - postgresql
    before_script:
      -  psql -c 'create database kids_krafts_test;' -U postgres
    script:
      - "python -m unittest discover tests"
